

task :default => :build

desc "Build a \"production\" Docker image from Github source"
task :build do
  sh "docker build --tag lazycache:latest ."
end

namespace :run do
  task :local do
    sh "docker run --rm --publish 8080:8080 lazycache:latest"
  end
end
