version: '3'
services:
  lazycache:
    build: ../../
    ports:
      - "8080:8080"
    volumes:
      - /data:/srv/overlay:ro
    environment:
      LAZYCACHE_FILEOVERLAY: /srv/overlay
      LAZYCACHE_FILEOVERLAY_FLATTEN: 1
      LAZYCACHE_ALLOW_RAW_OUTPUT: 1
