

# namespace :gcloud do
#   task :cred do
#     sh "gcloud config configurations activate lazycache-deis-dev"
#     sh "gcloud container  clusters get-credentials cluster-1"
#   end
# end

task :default => :test

task :build do
  sh "go build -o lazycache"
end

task :test => :build do
  sh "go test -tags integration"
end

task :profile do
  sh "go test -cpuprofile cpu_profile.out -tags profile -run TestOOIRootImageDecode -count 10"
  sh "go tool pprof -svg lazycache.test cpu_profile.out > cpu_profile.svg"
  sh "go tool pprof -top lazycache.test cpu_profile.out"
end


task :profile_server do
  trap('SIGINT') {}
  sh "./lazycache --cpuprofile cpu_profile.out"
  sh "go tool pprof -svg lazycache cpu_profile.out > cpu_profile.svg"
  sh "go tool pprof -top lazycache cpu_profile.out"
end

namespace :run do

  task :local => :build do
    sh *%w( ./lazycache
    --port 8080
    --bind 0.0.0.0 )
  end

  task :overlay => :build do
    sh *%w( ./lazycache
    --port 8080
    --bind 0.0.0.0
    --allow-raw-output
    --file-overlay /Users/aaron/workspace/go/src/github.com/amarburg/go-lazycache/app/overlay
    --file-overlay-flatten )

  end

  task :google_store => :build do
    sh(*%w( ./lazycache
            --port 8080
            --image-store google
            --image-store-bucket images-ooi-camhd-analytics
            --bind 127.0.0.1 ))
  end

  tmp_image_store = '/tmp/image_store'

  task :local_store => :build do
    mkdir(tmp_image_store) unless FileTest.directory? tmp_image_store

    sh(*%W( ./lazycache
            --port 8080
            --image-store local
            --image-store-root #{tmp_image_store}
            --image-store-url http://localhost:9082/
            --bind 127.0.0.1 ))
  end

  task :local_redis => :build do
    mkdir(tmp_image_store) unless FileTest.directory? tmp_image_store

#            --quicktime-store redis \

    sh "./lazycache \
            --port 8080 \
            --directory-store redis \
            --image-store local \
            --image-local-root #{tmp_image_store} \
            --image-url-root file://#{tmp_image_store} \
            --bind 127.0.0.1"
  end

end
