


namespace :docker do

  task :build do
    sh "docker build --tag amarburg/go-lazycache --no-cache ."
  end

  task :push do
    sh "docker push amarburg/go-lazycache"
  end

end

task :deploy do
  sh "gcloud compute instances create go-lazycache \
        --image-family gci-stable \
        --image-project google-containers \
        --address go-lazycache
        --metadata-from-file user-data=cloud-init \
        --tags http-server \
        --zone us-west1-a \
        --machine-type f1-micro"
end
