
class GCloudConfig
  attr_accessor :region, :name

  def initialize( name, args = {} )
    @region = args[:region] || 'us-central'

    @name = name
  end

  def url
    "http://#{name}.appspot.com/"
  end
end

config = GCloudConfig.new( 'camhd-app-dev-nocache' )


namespace :gcloud do

  # task :activate do
  #   sh *%W( gcloud config configurations activate #{camhd_app_dev.config} )
  # end

  task :create  do
    sh "gcloud --project=#{config.name} app create --region=#{config.region}"
  end

  task :deploy  do
    sh "gcloud --project=#{config.name} app deploy --stop-previous-version app.yaml"
  end

  task :open do
    sh "open #{camhd_app_dev.url()}"
  end

end

namespace :docker do

  task :build do
    sh *%w( docker build -t go-lazycache-appengine:dev . )
  end

  task :run do
    sh *%w( docker run --rm --publish 8080:8080 go-lazycache-appengine:dev )
  end

  task :console do
    sh *%w( docker run --rm --tty --interactive --entrypoint /bin/bash --publish-all go-lazycache-appengine:dev )
  end

end
